[package]
name = "working"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.23.1" #note crossterm version
coolor = {version = "0.5.0", features = ["crossterm"]}